[package]
name = "balance_query"
version = "0.1.0"
license-file = "LICENSE"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true

[lib]


[dependencies]
starknet = "2.9.0"
openzeppelin = "0.20.0"

[dev-dependencies]
snforge_std = "0.35.0"
